// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionItem = { id: string, pretty_id: string, summary: string, details: string | null, outcome: string | null, assignee: string | null, creator: string, question: string, status: string, assigned: string | null, resolved: string | null, created: string, };