// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateActionItemDetails } from "./CreateActionItemDetails";

export type CreateQuestionDetails = { pretty_id: string, summary: string, details: string | null, investigation: string, outcome: string | null, status: string, action_items: Array<CreateActionItemDetails>, };