// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateQuestionDetails } from "./CreateQuestionDetails";

export type CreateInvestigationDetails = { internal_id: string | null, first_name: string, middle_name: string | null, last_name: string, date_of_birth: string, namus_id: string | null, missing_since: string, synopsis: string, questions: Array<CreateQuestionDetails>, };