// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateActionItemDetails = { pretty_id: string, summary: string, details: string | null, outcome: string | null, assignee: string | null, status: string, resolved: string | null, };