// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Question } from "./Question";

export type Investigation = { id: string | null, created: string | null, internal_id: string | null, first_name: string, middle_name: string | null, last_name: string, date_of_birth: string, namus_id: string | null, missing_since: string, synopsis: string, questions: { [key: string]: Question } | null, };