// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type User = { id: string, email: string, display_name: string | null, enabled: boolean, created: string, otp: string | null, secret: string | null, otp_date: string | null, auth_date: string | null, };